name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run smoke tests every day at 5 AM EST (10 AM UTC)
    - cron: '0 10 * * *'
    # Run regression tests every alternate day at 7 AM EST (12 PM UTC)
    - cron: '0 12 */2 * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      # - name: Send email notification
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{ secrets.SMTP_USERNAME }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: Playwright Test Run ${{ job.status }}
      #     to: jalarahulreddy516@gmail.com
      #     from: Playwright CI <jalarahulreddy516@gmail.com>
      #     body: |
      #       The Playwright test run has completed with status: ${{ job.status }}.
      #       See details at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # - name: Send HTML report via email
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{ secrets.SMTP_USERNAME }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: Playwright Test Run ${{ job.status }}
      #     to: jalarahulreddy516@gmail.com
      #     from: Playwright CI <jalarahulreddy516@gmail.com>
      #     body: |
      #       The Playwright test run has completed with status: ${{ job.status }}.
      #       See details at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #     attachments: |
      #       playwright-report/index.html

  smoke:
    if: github.event_name == 'push' || (github.event_name == 'schedule' && github.event.schedule == '0 10 * * *')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright smoke tests
        run: npx playwright test --grep @smoke
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-smoke
          path: playwright-report/
      # - name: Send email notification
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{ secrets.SMTP_USERNAME }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: Playwright Smoke Test Run ${{ job.status }}
      #     to: jalarahulreddy516@gmail.com
      #     from: Playwright CI <jalarahulreddy516@gmail.com>
      #     body: |
      #       The Playwright smoke test run has completed with status: ${{ job.status }}.
      #       See details at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # - name: Send HTML report via email
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{ secrets.SMTP_USERNAME }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: Playwright Smoke Test Run ${{ job.status }}
      #     to: jalarahulreddy516@gmail.com
      #     from: Playwright CI <jalarahulreddy516@gmail.com>
      #     body: |
      #       The Playwright smoke test run has completed with status: ${{ job.status }}.
      #       See details at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #     attachments: |
      #       playwright-report/index.html

  regression:
    if: github.event_name == 'schedule' && github.event.schedule == '0 12 */2 * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright regression tests
        run: npx playwright test --grep @regression
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-regression
          path: playwright-report/
      # - name: Send email notification
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{ secrets.SMTP_USERNAME }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: Playwright Regression Test Run ${{ job.status }}
      #     to: jalarahulreddy516@gmail.com
      #     from: Playwright CI <jalarahulreddy516@gmail.com>
      #     body: |
      #       The Playwright regression test run has completed with status: ${{ job.status }}.
      #       See details at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # - name: Send HTML report via email
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{ secrets.SMTP_USERNAME }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: Playwright Regression Test Run ${{ job.status }}
      #     to: jalarahulreddy516@gmail.com
      #     from: Playwright CI <jalarahulreddy516@gmail.com>
      #     body: |
      #       The Playwright regression test run has completed with status: ${{ job.status }}.
      #       See details at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #     attachments: |
      #       playwright-report/index.html
